name: pulse_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dots_indicator: ^2.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  syncfusion_flutter_charts: ^19.2.56


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/vector.svg
  - assets/vector6.svg
  - assets/doubleLine.svg
  - assets/heart.svg
  - assets/highestCircle.svg
  - assets/highRectan.svg
  - assets/leftCircle.svg
  - assets/lineButton.svg
  - assets/middleCircle.svg
  - assets/middleRectan.svg
  - assets/rectangle.svg
  - assets/smallRectan.svg
  - assets/frame.svg
  - assets/image.svg
  - assets/innerHandPart.svg
  - assets/outHandPart.svg
  - assets/star.svg
  - assets/image.png
  - assets/thirdScreenImage.svg
  - assets/Rectangle.png
  - assets/fourScreenImage.png
  - assets/subscribeImage1.svg
  - assets/subscribeImage2.svg
  - assets/heartButton.svg
  - assets/Start.svg
  - assets/emojiBody.svg
  - assets/leftEmojiLeftEye.svg
  - assets/leftEmojiMouth.svg
  - assets/leftEmojiRightEye.svg
  - assets/middleEmojiEye.svg
  - assets/middleEmojiMouth.svg
  - assets/rightEmojiEye.svg
  - assets/rightEmojiMouth.svg
  - assets/leftColored.svg
  - assets/rightColored.svg
  - assets/middleColored.svg
  - assets/gray.svg
  - assets/clockFrame.svg
  - assets/feather.svg
  - assets/leftBookCover.svg
  - assets/leftBookPage.svg
  - assets/rightBookCover.svg
  - assets/rightBookPage.svg
  - assets/statisticsClockPointer.svg
  - assets/statisticsFrame.svg
  - assets/toLeft.svg
  - assets/toRight.svg
  - assets/historyFrame.svg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
